data:
  tokenizer: null
  train_files: ${data.train_path}
  val_files: ${data.val_path}
  train_path: /mnt/afs/tanka/shihao/project/data/kg_extraction/kg_extraction_train.jsonl
  val_path: /mnt/afs/tanka/shihao/project/data/kg_extraction/kg_extraction_val.jsonl
  prompt_key: prompt
  reward_fn_key: data_source
  max_prompt_length: 512
  max_response_length: 2048
  train_batch_size: 128
  val_batch_size: 32
  return_raw_input_ids: False
  return_raw_chat: False
  shuffle: True
  filter_overlong_prompts: False
  filter_overlong_prompts_workers: 1
  truncation: error
  image_key: images
  video_key: videos
  trust_remote_code: true
  include_reward_computation_in_dataset: false

actor_rollout_ref:
  hybrid_engine: True
  model:
    path: /mnt/afs/tanka/shihao/model/Qwen2.5-0.5B-Instruct
    external_lib: null
    override_config: { }
    enable_gradient_checkpointing: True
    use_remove_padding: False
    use_liger: False
  actor:
    strategy: fsdp
    ppo_mini_batch_size: 16
    ppo_micro_batch_size: 8
    ppo_micro_batch_size_per_gpu: null
    micro_batch_size: 8
    micro_batch_size_per_gpu: null
    use_dynamic_bsz: False
    ppo_max_token_len_per_gpu: 16384
    grad_clip: 1.0
    clip_ratio: 0.2
    clip_ratio_low: 0.2
    clip_ratio_high: 0.2
    clip_ratio_c: 3.0
    loss_agg_mode: "token-mean"
    entropy_coeff: 0.0
    use_kl_loss: true
    use_torch_compile: True
    kl_loss_coef: 0.1
    kl_loss_type: low_var_kl
    ppo_epochs: 4
    shuffle: False
    ulysses_sequence_parallel_size: 1
    checkpoint:
      contents: ['model', 'optimizer', 'extra']
    optim:
      lr: 5e-6
      lr_warmup_steps: -1
      lr_warmup_steps_ratio: 0.0
      min_lr_ratio: null
      warmup_style: constant
      total_training_steps: -1
      weight_decay: 0.01
    fsdp_config:
      wrap_policy:
        min_num_params: 0
      param_offload: False
      optimizer_offload: False
      offload_policy: False
      reshard_after_forward: true
      move_params_to_cpu: false
      state_dict_type: full
      fsdp_size: -1
  ref:
    strategy: fsdp
    fsdp_config:
      param_offload: False
      reshard_after_forward: True
      wrap_policy:
        min_num_params: 0
    use_torch_compile: ${actor_rollout_ref.actor.use_torch_compile}
    log_prob_micro_batch_size: 8
    log_prob_micro_batch_size_per_gpu: null
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    ulysses_sequence_parallel_size: ${actor_rollout_ref.actor.ulysses_sequence_parallel_size}
  rollout:
    name: vllm
    mode: sync
    chat_scheduler: null
    temperature: 0.8
    top_k: -1
    top_p: 0.9
    use_fire_sampling: False
    prompt_length: ${data.max_prompt_length}
    response_length: ${data.max_response_length}
    dtype: bfloat16
    gpu_memory_utilization: 0.5
    ignore_eos: False
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy_dtensor
    tensor_model_parallel_size: 1
    max_num_batched_tokens: 8192
    max_model_len: null
    max_num_seqs: 1024
    log_prob_micro_batch_size: 8
    log_prob_micro_batch_size_per_gpu: null
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    disable_log_stats: True
    enable_chunked_prefill: True
    do_sample: True
    n: 1
    engine_kwargs:
      swap_space: null
    val_kwargs:
      top_k: -1
      top_p: 1.0
      temperature: 0
      n: 1
      do_sample: False
    multi_turn:
      enable: False
      max_turns: null
      tool_config_path: null
      format: chatml

critic:
  rollout_n: ${actor_rollout_ref.rollout.n}
  strategy: fsdp
  optim:
    lr: 5e-6
    lr_warmup_steps_ratio: 0.0
    min_lr_ratio: null
    warmup_style: constant
    total_training_steps: -1
    weight_decay: 0.01
  model:
    path: /mnt/afs/tanka/shihao/model/Qwen2.5-0.5B-Instruct
    tokenizer_path: ${actor_rollout_ref.model.path}
    override_config: { }
    external_lib: ${actor_rollout_ref.model.external_lib}
    enable_gradient_checkpointing: True
    use_remove_padding: False
    fsdp_config:
      param_offload: False
      optimizer_offload: False
      offload_policy: False
      reshard_after_forward: true
      move_params_to_cpu: false
      state_dict_type: full
      wrap_policy:
        min_num_params: 0
      fsdp_size: -1
  ppo_mini_batch_size: ${actor_rollout_ref.actor.ppo_mini_batch_size}
  ppo_micro_batch_size: 8
  ppo_micro_batch_size_per_gpu: null
  micro_batch_size: 8
  micro_batch_size_per_gpu: null
  forward_micro_batch_size: null
  forward_micro_batch_size_per_gpu: null
  use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
  ppo_max_token_len_per_gpu: 32768
  forward_max_token_len_per_gpu: ${critic.ppo_max_token_len_per_gpu}
  ulysses_sequence_parallel_size: 1
  ppo_epochs: ${actor_rollout_ref.actor.ppo_epochs}
  shuffle: ${actor_rollout_ref.actor.shuffle}
  grad_clip: 1.0
  cliprange_value: 0.5
  checkpoint:
    contents: ['model', 'optimizer', 'extra']

reward_model:
  enable: false
  strategy: fsdp
  model:
    input_tokenizer: ${actor_rollout_ref.model.path}
    path: null
    external_lib: ${actor_rollout_ref.model.external_lib}
    use_remove_padding: False
    fsdp_config:
      wrap_policy:
        min_num_params: 0
      param_offload: False
      reshard_after_forward: True
      fsdp_size: -1
  micro_batch_size: 8
  micro_batch_size_per_gpu: null
  max_length: null
  ulysses_sequence_parallel_size: 1
  use_dynamic_bsz: ${critic.use_dynamic_bsz}
  forward_max_token_len_per_gpu: ${critic.forward_max_token_len_per_gpu}
  reward_manager: naive
  launch_reward_fn_async: False

custom_reward_function:
  path: /mnt/afs/tanka/shihao/project/verl/verl/utils/kg_rewards.py
  name: compute_kg_extraction_reward
  reward_kwargs:
    threshold: 0.5

algorithm:
  gamma: 1.0
  lam: 0.95
  adv_estimator: gae
  norm_adv_by_std_in_grpo: True
  use_kl_in_reward: true
  kl_penalty: kl
  kl_ctrl:
    type: fixed
    kl_coef: 0.1
    horizon: 10000
    target_kl: 0.2

trainer:
  balance_batch: True
  total_epochs: 30
  total_training_steps: null
  project_name: kg_extraction
  experiment_name: kg_extraction
  logger: [ 'console', 'wandb' ]
  log_val_generations: 0
  rollout_data_dir: null
  validation_data_dir: null
  nnodes: 1
  n_gpus_per_node: 2
  save_freq: 2
  resume_mode: auto
  resume_from_path: null
  val_before_train: True
  test_freq: 1
  critic_warmup: 0
  default_hdfs_dir: null
  del_local_ckpt_after_load: False
  default_local_dir: checkpoints/${trainer.project_name}/${trainer.experiment_name}
  max_actor_ckpt_to_keep: null
  max_critic_ckpt_to_keep: null
  ray_wait_register_center_timeout: 300
  output_dir: /mnt/afs/tanka/shihao/outputs/kg_extraction

ray_init:
  num_cpus: 32

quick_test_mode: false